### ISSUE TITLE
sourcegraph/docs#241: "update Cody supported languages list"

### ISSUE THREAD

**Issue by sourcegraph-bot-devx** [sourcegraph/sec-pr-audit-trail#475]
https://github.com/sourcegraph/docs/pull/241 "update Cody supported languages list" **has a test plan (or does not require one)** but **was not reviewed**.

@sqs please comment in this issue with an explanation for this exception and close this issue.

**Comment by sqs** [comment]
I force-merged this PR to our docs repo to update the list of supported languages FAQ answer and fix a typo because it was in a top comment on HN: https://github.com/sourcegraph/sec-pr-audit-trail/issues/475 https://news.ycombinator.com/item?id=39965825

See https://sourcegraph.slack.com/archives/C1JH2BEHZ/p1712544926788349.
